use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use tokio::process::Child;
use tokio::task::AbortHandle;
use uuid::Uuid;

use crate::confirm_tokens::ConfirmTokenStore;
use crate::db::driver::Driver;
use crate::error::{AppError, AppResult};
use crate::schema_cache::SchemaCache;

/// One live driver per connection id.
#[derive(Default)]
pub struct AppState {
    pub conns: Mutex<HashMap<Uuid, Arc<dyn Driver>>>,
    /// In-flight queries by id (query id is a string generated by the frontend).
    pub running: Mutex<HashMap<String, AbortHandle>>,
    /// SSH tunnel processes by connection id.
    pub tunnels: Mutex<HashMap<Uuid, Child>>,
    /// Per-connection schema catalog cache.
    pub schema_cache: SchemaCache,
    pub confirm_tokens: ConfirmTokenStore,
}

impl AppState {
    pub fn register_query(&self, query_id: String, handle: AbortHandle) {
        self.running.lock().unwrap().insert(query_id, handle);
    }
    pub fn finish_query(&self, query_id: &str) {
        self.running.lock().unwrap().remove(query_id);
    }
    pub fn cancel(&self, query_id: &str) {
        if let Some(h) = self.running.lock().unwrap().remove(query_id) {
            h.abort();
        }
    }

    pub fn get(&self, id: Uuid) -> AppResult<Arc<dyn Driver>> {
        self.conns
            .lock()
            .unwrap()
            .get(&id)
            .cloned()
            .ok_or_else(|| AppError::ConnectionNotFound(id.to_string()))
    }

    pub fn insert(&self, id: Uuid, driver: Arc<dyn Driver>) {
        self.conns.lock().unwrap().insert(id, driver);
    }

    pub fn insert_tunnel(&self, id: Uuid, child: Child) {
        self.tunnels.lock().unwrap().insert(id, child);
    }

    pub fn remove(&self, id: Uuid) {
        if let Some(driver) = self.conns.lock().unwrap().remove(&id) {
            tokio::spawn(async move { driver.close().await });
        }
        self.tunnels.lock().unwrap().remove(&id);
        self.schema_cache.drop_entry(id);
    }
}
